### PR TITLE
Validate user identity and roles before hub name.

### LINKED ISSUE #313: Identity should be validated before validating the task hub name.
When navigating to an invalid URL in the DFM, an unauthorized/unauthenticated user will encounter a `Task Hub name is invalid` error message before their identity is validated.

To reproduce this, navigate to `<dfm url>/z` in an unauthenticated context and note that the user's identity is not validated before responding with `Task Hub name is invalid.`

### PR DESCRIPTION
**Pull request by EvanSchallerer**
Validates the user's identity before validating the hub name.

Closes #313

### CODE REVIEW

**Comment by EvanSchallerer** [comment]
@microsoft-github-policy-service agree company="Cosmos Data Technologies, Inc."

File: durablefunctionsmonitor.dotnetbackend/Common/Auth.cs [hunk 1]
```diff
@@ -100,15 +100,10 @@ public static async Task<DfmMode> ValidateIdentityAsync(ClaimsPrincipal principa
...
-            // Validating Task Hub name, if it was specified
-            if (!string.IsNullOrEmpty(taskHubName))
-            {
-                await ThrowIfTaskHubNameIsInvalid(taskHubName);
-            }
-
             // Starting with nonce (used when running as a VsCode extension)
             if (IsNonceSetAndValid(headers))
             {
+                await ThrowIfTaskHubNameIsInvalid(taskHubName);
```
Comment (scale-tone) [inline durablefunctionsmonitor.dotnetbackend/Common/Auth.cs]: To simplify the logic (so that you don't have to call ThrowIfTaskHubNameIsInvalid() in four different places) consider just excluding task hub name validation from this method and instead validate it as the next step, after ValidateIdentityAsync() is being called.

Comment (EvanSchallerer) [reply durablefunctionsmonitor.dotnetbackend/Common/Auth.cs]: That change has been applied, thanks!

**Comment by scale-tone** [comment]
Thanks @EvanSchallerer , great stuff!
